philips-software/docker-blackduck

- CHANGELOG.md
- CODEOWNERS
> Adds CODEOWNERS file

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
> chore: 🤖 Rename repository name

- 5/java/Dockerfile
- 5/node/Dockerfile
This is in preparation of an upcoming airgap PR
> Use arg for Blackduck version

- 5/java/Dockerfile
- 5/java/scripts/entrypoint.sh
- README.md
- Adds Air Gap mode (Gradle only for now)
- Support Gradle builds behind proxy (sets GRADLE_OPTS)
- Updated README.md
> Support Air Gap mode. Fixes #9

- .github/workflows/build_docker.yml
- 6/dotnetcore/Dockerfile
- CHANGELOG.md
- README.md
Support for dotnet:3.0.101-sdk added
> Added support for .net core

- 6/dotnetcore/Dockerfile
- README.md
> Uses default java jre

- .github/workflows/build_docker.yml
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-2.2.110/scripts/entrypoint.sh
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.0.101/scripts/entrypoint.sh
- README.md
Support for .net core 2.2.110 added. Also enabled airgap for .net core images
> Add support for dotnet core 2 2 110

- 6/dotnetcore-2.2.110/Dockerfile
The dotnet executable path was wrong corrected it
> Dotnet 2 2 110 update dotnet path

- .github/workflows/build_docker.yml
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- CHANGELOG.md
- README.md
- Upgrade synopsys-detect to version to 6.1.0
> Bump to 6.1.0

- .github/workflows/build_docker.yml
- 6/dotnetcore-3.1.102/Dockerfile
- 6/dotnetcore-3.1.102/scripts/entrypoint.sh
- README.md
.NET Core 3.1 support added. 
.NET 2.x runtime also included into the image which is dependency of nuget_inspector.
> Added support for dotnetcore 3.1

- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.1.102/Dockerfile
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- CHANGELOG.md
> add nc tool

- .github/workflows/build_docker.yml
- 6/java/Dockerfile
- 6/node/Dockerfile
Closes #31 
Base java image was moved to alpine, causing some troubles scanning projects.
> Switch to older java

- .github/workflows/build_docker.yml
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.1.102/Dockerfile
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- README.md
Bump Synopsys detect version to 6.3.0
> Bump Synopsys detect version to 6.3.0

- .github/workflows/add-contributors.yml
- .github/workflows/build_docker.yml
- README.md
Same as for docker-whitesource. Faces of the contributors are added when pushed to master.
> Add faces-contributors with Pull requests and updated build scripts

- .github/dependabot.yml
- .github/workflows/build_docker.yml
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.1.302/Dockerfile
- 6/dotnetcore-3.1.302/scripts/entrypoint.sh
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- CHANGELOG.md
- README.md
Update detect to 6.4.0
Update versions of languages according to #41 #42 and #43
> update versions and detect to 6.4.0 after getting hints from dependabot

- .github/workflows/build_docker.yml
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.1.102/Dockerfile
- 6/dotnetcore-3.1.302/Dockerfile
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- CHANGELOG.md
- CODEOWNERS
- README.md
Detect version 6.5.0 is available.
This PR updates the detect version.
> update detect to 6.5.0

- 6/docker/Dockerfile
> fix permissions on blackduck-docker-inspector.sh in example 

- .github/workflows/build_docker.yml
- 6/docker/Dockerfile
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.1.102/Dockerfile
- 6/dotnetcore-3.1.302/Dockerfile
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- CHANGELOG.md
- README.md
@JeroenKnoops , can you please review?
> Updated the version from 6.5.0 to 6.7.0

- .github/workflows/build_docker.yml
- 6/python/Dockerfile
- README.md
> add python image

- 6/python/Dockerfile
> Add poetry

- .github/workflows/build_docker.yml
- 6/docker/Dockerfile
- 6/dotnetcore-2.2.110/Dockerfile
- 6/dotnetcore-3.0.101/Dockerfile
- 6/dotnetcore-3.1.102/Dockerfile
- 6/dotnetcore-3.1.302/Dockerfile
- 6/golang/Dockerfile
- 6/java/Dockerfile
- 6/node/Dockerfile
- 6/python/Dockerfile
- CHANGELOG.md
- README.md
See release notes:
https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/642351242/Releases+Notes
Closes #103
> Update scanner version to 6.9.1

- .github/workflows/build_docker.yml
- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- README.md
Upgrade to new version of detect [7.1.0](https://sig-repo.synopsys.com/ui/native/bds-integrations-release/com/synopsys/integration/synopsys-detect/7.1.0)
<https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/642351242/Releases+Notes>
<https://sig-repo.synopsys.com/ui/native/bds-integrations-release/com/synopsys/integration/synopsys-detect/>
> Upgrade detect to 7.1.0

- .github/workflows/build_docker.yml
- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- CHANGELOG.md
- README.md
New version is release:
https://github.com/blackducksoftware/synopsys-detect/releases/tag/7.4.0
Release Notes:
https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/642351242/Releases+Notes
> Update to version 7.4.0 of scanner

- .github/workflows/build_docker.yml
- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- README.md
New release is available.
https://github.com/blackducksoftware/synopsys-detect/releases/tag/7.8.0
> Use version 7.8.0

- 7/java/Dockerfile
> Upgrade Maven from 3.8.3 to 3.8.4

- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- CHANGELOG.md
Remove `--blackduck.hub.trust.cert=true`
> Remove insecure cert arg

- .github/workflows/build_docker.yml
- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- README.md
Update to latest version of Detect.
https://github.com/blackducksoftware/synopsys-detect/releases/tag/7.9.0
> Update to detect version 7.9.0

- .github/workflows/build_docker.yml
- cosign.pub
Add SLSA Provenance to docker containers.
Now using a branch release of docker-ci-scripts. Waiting for official release of Docker CI scripts.
- https://github.com/philips-software/docker-ci-scripts/pull/94
- https://github.com/philips-software/docker-ci-scripts/pull/95
> Add provenance and refactor build workflow

- .github/workflows/build_docker.yml
- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- CHANGELOG.md
- README.md
Synopsis release detect scanner version 7.13.2
> Update scanner 7.13.2

- .github/workflows/build_docker.yml
- 7/docker/Dockerfile
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- CHANGELOG.md
- README.md
Update to Blackduck scanner version: 7.14.0
> blackduck scanner version 7.14.0

- .github/workflows/build_docker.yml
- CHANGELOG.md
Use new arguments `REGISTRY_USERNAME` and `REGISTRY_TOKEN`
> Use new arguments for container registry

- .github/workflows/build_docker.yml
- 7/dotnetcore-2.2.110/Dockerfile
- 7/dotnetcore-3.0.101/Dockerfile
- 7/dotnetcore-3.1.102/Dockerfile
- 7/dotnetcore-3.1.302/Dockerfile
- 7/golang/Dockerfile
- 7/java/Dockerfile
- 7/node/Dockerfile
- 7/python/Dockerfile
- cosign.pub
> Use SigStore's keyless signing with Rekor

- .github/workflows/build_docker.yml
- 8/dotnetcore-2.2.110/Dockerfile
- 8/dotnetcore-3.0.101/Dockerfile
- 8/dotnetcore-3.1.102/Dockerfile
- 8/dotnetcore-3.1.302/Dockerfile
- 8/golang/Dockerfile
- 8/java/Dockerfile
- 8/node/Dockerfile
- 8/python/Dockerfile
- CHANGELOG.md
Version 8.2.0 has been released.
> Upgrade to version 8.2.0

- .github/workflows/build_docker.yml
- 8/dotnetcore-2.2.110/Dockerfile
- 8/dotnetcore-3.0.101/Dockerfile
- 8/dotnetcore-3.1.102/Dockerfile
- 8/dotnetcore-3.1.302/Dockerfile
- 8/golang/Dockerfile
- 8/java/Dockerfile
- 8/node/Dockerfile
- 8/python/Dockerfile
- CHANGELOG.md
Detect 8.3.0 is out! Let's start using that!
> Update to detect version 8.3.0

- .github/workflows/build_docker.yml
- 7/java/Dockerfile
- 8/dotnetcore-2.2.110/Dockerfile
- 8/dotnetcore-3.0.101/Dockerfile
- 8/dotnetcore-3.1.102/Dockerfile
- 8/dotnetcore-3.1.302/Dockerfile
- 8/golang/Dockerfile
- 8/java/Dockerfile
- 8/node/Dockerfile
- 8/python/Dockerfile
- CHANGELOG.md
Update version of detect to 8.5.0
Update version of maven to 3.8.7
> Update version of detect and maven
